name       : openjpeg
version    : 2.3.1
release    : 19
source     :
    - https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz : 63f5a4713ecafc86de51bfad89cc07bb788e9bba24ebbf0c4ca637621aadb6a9
license    : BSD-2-Clause
component  : multimedia.library
summary    : An open-source JPEG 2000 codec written in C
description: |
    OpenJPEG is an open-source JPEG 2000 codec written in C language. It has been developed in order to promote the use of JPEG 2000, a still-image compression standard from the Joint Photographic Experts Group (JPEG). Since April 2015, it is officially recognized by ISO/IEC and ITU-T as a JPEG 2000 Reference Software.
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
setup      : |
    %apply_patches
    %cmake -DOPENJPEG_INSTALL_LIB_DIR=lib%LIBSUFFIX% \
        -DBUILD_STATIC_LIBS=OFF .
build      : |
    %make
install    : |
    %make_install
