name       : openjpeg
version    : 1.5.2
release    : 2
source     :
    - https://github.com/uclouvain/openjpeg/archive/version.1.5.2.tar.gz : 3734e95edd0bef6e056815591755efd822228dc3cd866894e00a2c929026b16d
license    : BSD-2-Clause
summary    : An open-source JPEG 2000 codec written in C.
description: |
    An open-source JPEG 2000 codec written in C.
builddeps  :
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
