name       : openjpeg
version    : 2.1.2
release    : 3
source     :
    - https://github.com/uclouvain/openjpeg/archive/v2.1.2.tar.gz : 4ce77b6ef538ef090d9bde1d5eeff8b3069ab56c4906f083475517c2c023dfa7
license    : BSD-2-Clause
component  : multimedia.library
summary    : An open-source JPEG 2000 codec written in C.
description: |
    An open-source JPEG 2000 codec written in C.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
