name       : openjpeg
version    : 2.2.0
release    : 11
source     :
    - git|https://github.com/uclouvain/openjpeg.git : 28094e1ebfa420f9a0bdc7a11b8d4ee5f154db35
license    : BSD-2-Clause
component  : multimedia.library
summary    : An open-source JPEG 2000 codec written in C.
description: |
    OpenJPEG is an open-source JPEG 2000 codec written in C language. It has been developed in order to promote the use of JPEG 2000, a still-image compression standard from the Joint Photographic Experts Group (JPEG). Since April 2015, it is officially recognized by ISO/IEC and ITU-T as a JPEG 2000 Reference Software.
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
setup      : |
    %apply_patches
    %cmake -DOPENJPEG_INSTALL_LIB_DIR=%libdir% .
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/lib64/lib*.a
