name       : openjpeg
version    : 2.1.0
release    : 4
source     :
    - https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz : 4afc996cd5e0d16360d71c58216950bcb4ce29a3272360eb29cadb1c8bce4efc
license    : BSD-2-Clause
component  : multimedia.library
summary    : An open-source JPEG 2000 codec written in C.
description: |
    An open-source JPEG 2000 codec written in C.
setup      : |
    %apply_patches
    %cmake .
build      : |
    %make
install    : |
    %make_install
