name       : openjpeg
version    : 2.1.1
release    : 6
source     :
    - https://github.com/uclouvain/openjpeg/archive/v2.1.1.tar.gz : 82c27f47fc7219e2ed5537ac69545bf15ed8c6ba8e6e1e529f89f7356506dbaa
license    : BSD-2-Clause
component  : multimedia.library
summary    : An open-source JPEG 2000 codec written in C.
description: |
    An open-source JPEG 2000 codec written in C.
setup      : |
    %apply_patches
    %cmake .
build      : |
    %make
install    : |
    %make_install
